pipeline {
    agent any

  tools {nodejs "node17"}

    stages {
        stage('Dependencies') {
            steps {
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/ajhernandezr/ArChallenge.git'
            }
        }
        stage('Build') {
            steps {
                sh 'yarn install'
            }
        }
        stage('Unit Tests') {
            steps {
                echo 'Unit test'
            }
        }
        stage('e2e Tests') {
            steps {
                sh 'yarn'
                sh 'yarn cypress run'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
         post {
            always {
         }
    }
}
